# Generated by Django 5.2.6 on 2025-10-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='strand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
