# Generated by Django 5.2.6 on 2025-10-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_school_year_profile_strand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
